US691069: QoQ Auto tune the target queue lengths based on average consumption rates
WorkerFramework/worker-message-prioritization pull request #43
Opened 2023-06-21 10:00 UTC by caoimhelynch

https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=691069

2023-06-21 10:18 UTC, buildmachine-sou-jenkins2 commented
CI Build Link:
http://sou-jenkins2.swinfra.net:8080/job/WorkerFramework/job/WorkerFramework~worker-message-prioritization~US691069~CI

2023-06-22 10:02 UTC, andyreidz requested changes
Thanks Caoimhe, great work.

2023-06-22 10:02 UTC, andyreidz commented on worker-message-prioritization-target-capacity-calculators/src/test/java/com/github/workerframework/workermessageprioritization/redistribution/TunedTargetQueueLengthProviderTest.java
> +    public void getTunedTargetQueueForQueueWithInadequateHistoryAndNoOpModeOffTest(){
What's highlighting this possible redundancy is that the asserts are the same for both tests, implying that the variables in parameters between both tests have no impact on the result.

<img width="1242" alt="image" src="https://github.com/WorkerFramework/worker-message-prioritization/assets/18459684/391b1adb-2e2a-46f4-b419-0407cc1d7e3e">

<img width="1231" alt="image" src="https://github.com/WorkerFramework/worker-message-prioritization/assets/18459684/2180300d-ca8b-44f2-836e-fc1f637c9e22">

2023-06-22 10:02 UTC, andyreidz commented on worker-message-prioritization-target-capacity-calculators/src/test/java/com/github/workerframework/workermessageprioritization/redistribution/TunedTargetQueueLengthProviderTest.java
> +    public void getMinTunedTargetQueueNoOpTest(){
Will leave reviewing the rest of the tests until you have a chance to apply current feedback.

2023-06-22 10:04 UTC, andyreidz commented
I forgot to highlight the format for logging statements.

<img width="982" alt="image" src="https://github.com/WorkerFramework/worker-message-prioritization/assets/18459684/10d0749b-edbe-49d6-b936-19967f0c9460">

The above avoids building the log message when the log level is disabled.

Also if you wanto still have the logs generated during build, set the CAF_LOG_LEVEL to DEBUG in the failsafe plugin configuration.

2023-07-03 11:24 UTC, andyreidz requested changes
Looks good, some small comments about formatting and checking for exceptions in tests.

Can you also move to using this style of logging?

LOGGER.debug("Target queue length has been rounded from: " + tunedTargetQueue + " to:" + roundedQueueLength);

LOGGER.debug("Target queue length has been rounded from: {} to {}", tunedTargetQueue , roundedQueueLength);

2023-07-03 11:24 UTC, andyreidz commented on worker-message-prioritization-target-capacity-calculators/src/test/java/com/github/workerframework/workermessageprioritization/redistribution/HistoricalConsumptionRateTest.java
> +            fail();
```suggestion
            fail("IllegalArgumentException was not thrown");
```

2023-07-03 11:24 UTC, andyreidz commented on worker-message-prioritization-target-capacity-calculators/src/test/java/com/github/workerframework/workermessageprioritization/redistribution/HistoricalConsumptionRateTest.java
> +            assertNotNull("IllegalArgumentException was not thrown", exception);
```suggestion
```
exception can't be null here

2023-07-03 11:24 UTC, andyreidz commented on worker-message-prioritization-target-capacity-calculators/src/test/java/com/github/workerframework/workermessageprioritization/redistribution/HistoricalConsumptionRateTest.java
> +            assertNotNull("IllegalArgumentException was not thrown", exception);
Apply the same change where required.

2023-07-03 11:24 UTC, andyreidz commented on worker-message-prioritization-target-capacity-calculators/src/test/java/com/github/workerframework/workermessageprioritization/redistribution/HistoricalConsumptionRateTest.java
> +        final boolean theoreticalConsumptionRateHistoryQueue1 = historicalConsumptionRate.isSufficientHistoryAvailable(targetQueue1);
```suggestion
        final boolean isSufficientHistoryAvailableQueue1 = historicalConsumptionRate.isSufficientHistoryAvailable(targetQueue1);
```

2023-07-03 11:24 UTC, andyreidz commented on worker-message-prioritization-target-capacity-calculators/src/test/java/com/github/workerframework/workermessageprioritization/redistribution/HistoricalConsumptionRateTest.java
> +        final boolean theoreticalConsumptionRateHistoryQueue2 = historicalConsumptionRate.isSufficientHistoryAvailable(targetQueue2);
```suggestion
        final boolean isSufficientHistoryAvailableQueue2 = historicalConsumptionRate.isSufficientHistoryAvailable(targetQueue2);
```

2023-07-03 11:24 UTC, andyreidz commented on worker-message-prioritization-target-capacity-calculators/src/test/java/com/github/workerframework/workermessageprioritization/redistribution/RoundTargetQueueLengthTest.java
> +    public void getRoundedTargetQueueLengthTest() {
Minor one, spaces after commas 👇

2023-07-03 11:24 UTC, andyreidz commented on worker-message-prioritization-target-capacity-calculators/src/test/java/com/github/workerframework/workermessageprioritization/redistribution/RoundTargetQueueLengthTest.java
> +            assertNotNull("IllegalArgumentException was not thrown", exception);
Apply previous comment use "IllegalArgumentException was not thrown" in the fail() and remove the assertNotNull

2023-07-03 11:24 UTC, andyreidz commented on worker-message-prioritization-target-capacity-calculators/src/test/java/com/github/workerframework/workermessageprioritization/redistribution/TunedTargetQueueLengthProviderTest.java
> +        assertEquals("NoOpMode is on: Target queue length should not have changed.Suggested adjustment for the target queue length " +
```suggestion
        assertEquals("NoOpMode is on: Target queue length should not have changed. Suggested adjustment for the target queue length " +
```

2023-07-03 11:24 UTC, andyreidz commented on worker-message-prioritization-target-capacity-calculators/src/test/java/com/github/workerframework/workermessageprioritization/redistribution/TunedTargetQueueLengthProviderTest.java
> +        final long tunedTargetQueueLength = getTunedTargetQueueLength(targetQueue1,targetQueue);
```suggestion
        final long tunedTargetQueueLength = getTunedTargetQueueLength(targetQueue1, targetQueue);
```

2023-08-03 11:00 UTC, caoimhelynch commented on worker-message-prioritization-distribution/src/test/java/com/github/workerframework/workermessageprioritization/redistribution/consumption/MinimumConsumptionTargetCalculatorTest.java
> +        final TargetQueueSettings settings = new TargetQueueSettings(1000, 20, 1, 1);
Have altered these to make the different in the tests more clear.

2023-09-13 15:11 UTC, closed without merging